### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#36]
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 783: ordinal not in range(128)
    '[fc] {0}'.format(changeset),
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/views/runcorejob.py", line 78, in commit_to_coredev
    timestamp,
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/views/runcorejob.py", line 231, in run_function_core_tests
    return fn(request)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/security.py", line 20, in wrapped
    response = view_(request)
  File "/srv/mr.roboto/eggs/cornice-1.2.0-py2.7.egg/cornice/service.py", line 573, in wrapper
    response = view(request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 507, in _requestonly_view
    result = view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 353, in rendered_view
    return view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 602, in __call__
    response = view_callable(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/view.py", line 541, in _call_view
    view_name
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 145, in handle_request
    response = handler(request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    result = view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    response = view_callable(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/view.py", line 541, in _call_view
    request_iface=request_iface.combined
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/tweens.py", line 48, in excview_tween
    response = handle_request(request)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 198, in invoke_subrequest
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/srv/mr.roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 223, in __call__
    return app(environ, start_response)
  File "/srv/mr.roboto/eggs/Paste-2.0.3-py2.7.egg/paste/urlmap.py", line 216, in __call__
    app_iter = self.channel.server.application(env, start_response)
  File "/srv/mr.roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
    self.execute()
  File "/srv/mr.roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
    task.service()
  File "/srv/mr.roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
Traceback (most recent call last):
```

Note that the traceback is reversed, the last step is at the top

**Comment by gforcada** [comment]
We are on py3 already ! 🎉
