### ISSUE TITLE
Handle SMTPServerDisconnected when sending emails

### ISSUE THREAD

**Issue by gforcada** [plone/mr.roboto#43]
Handle this:

```
2017-07-07 14:57:30,211 ERROR [waitress][waitress] Exception when serving /run/corecommit
Traceback (most recent call last):
  File "roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
    task.service()
  File "roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "roboto/eggs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "roboto/eggs/Paste-2.0.3-py2.7.egg/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/tweens.py", line 48, in excview_tween
    request_iface=request_iface.combined
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/router.py", line 145, in handle_request
    view_name
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "roboto/eggs/cornice-1.2.0-py2.7.egg/cornice/service.py", line 573, in wrapper
    response = view_(request)
  File "roboto/src/mr.roboto/src/mr/roboto/security.py", line 20, in wrapped
    return fn(request)
  File "roboto/src/mr.roboto/src/mr/roboto/views/runcorejob.py", line 170, in run_function_core_tests
    request.registry.notify(NewCoreDevPush(payload, request))
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/registry.py", line 91, in notify
    [ _ for _ in self.subscribers(events, None) ]
  File "roboto/eggs/zope.interface-4.1.3-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 328, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "roboto/eggs/zope.interface-4.1.3-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 596, in subscribers
    subscription(*objects)
  File "roboto/eggs/pyramid-1.6.1-py2.7.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
    return subscriber(arg[0])
  File "roboto/src/mr.roboto/src/mr/roboto/subscriber.py", line 118, in send_mail_on_coredev
    mail_to_cvs(payload, mailer)
  File "roboto/src/mr.roboto/src/mr/roboto/subscriber.py", line 109, in mail_to_cvs
    mailer.send_immediately(msg, fail_silently=False)
  File "roboto/eggs/pyramid_mailer-0.14.1-py2.7.egg/pyramid_mailer/mailer.py", line 275, in send_immediately
    return self.smtp_mailer.send(*self._message_args(message))
  File "roboto/eggs/repoze.sendmail-4.2-py2.7.egg/repoze/sendmail/mailer.py", line 100, in send
    connection.sendmail(fromaddr, toaddrs, message)
  File "/srv/python2.7.11/lib/python2.7/smtplib.py", line 743, in sendmail
    (code, resp) = self.data(msg)
  File "/srv/python2.7.11/lib/python2.7/smtplib.py", line 511, in data
    (code, msg) = self.getreply()
  File "/srv/python2.7.11/lib/python2.7/smtplib.py", line 365, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: ('The read operation timed out',)
```

**Comment by gforcada** [comment]
With #130 we don't have to care about those 😄
