### ISSUE TITLE
It is not possible to run the KGS jobs manually.

### ISSUE THREAD

**Issue by tisto** [plone/mr.roboto#9]
The KGS jobs always fail when run manually, see for instance:

http://jenkins.plone.org/view/KGS/job/kgs-plone.app.discussion-plone-5.0-python-2.7/11/console

```
Deleting project workspace... Checkout:kgs-plone.app.discussion-plone-5.0-python-2.7 / /home/jenkins/workspace/kgs-plone.app.discussion-plone-5.0-python-2.7 - hudson.remoting.Channel@72e55df0:Slave3
Using strategy: Default
Last Built Revision: Revision 27f5c52e40aca17faf8e55d8ebb1d4b51b0a8a20 (origin/5.0)
Cloning the remote Git repository
Cloning repository git://github.com/plone/buildout.coredev.git
git --version
git version 1.7.9.5
Fetching upstream changes from origin
Commencing build of Revision 67d351f52d1f213575197f17ddbf0b4d5a73a916 (origin/5.0)
Checking out Revision 67d351f52d1f213575197f17ddbf0b4d5a73a916 (origin/5.0)
No emails were triggered.
Allocating TCP port ZSERVER_PORT
  -> Assigned 55067
TCP port allocation complete
Xvfb starting$ /usr/bin/Xvfb :3 -screen 0 1024x768x24 -fbdir /home/jenkins/2013-12-15_15-29-59104090435136381791xvfb
[kgs-plone.app.discussion-plone-5.0-python-2.7] $ /bin/bash -xe /tmp/hudson393224501184016831.sh
+ echo 'Save to CHANGES.log'
Save to CHANGES.log
+ wget No changes -O CHANGES.log
--2013-12-15 17:28:21--  http://no/
Resolving no (no)... failed: Name or service not known.
wget: unable to resolve host address `no'
--2013-12-15 17:28:21--  http://changes/
Resolving changes (changes)... failed: Name or service not known.
wget: unable to resolve host address `changes'
Build step 'Execute shell' marked build as failure
Xvfb stopping
Recording test results
Robot results publisher started...
-Parsing output xml:
Failed!
/home/jenkins/workspace/kgs-plone.app.discussion-plone-5.0-python-2.7/parts/jenkins-test does not exist.
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:483)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:460)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:65)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:51)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2387)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:679)
No emails were triggered.
Perfrom custom history collecting to file:CHANGES.log
**ArtifactsFile= /opt/bitnami/apps/jenkins/jenkins_home/jobs/kgs-plone.app.discussion-plone-5.0-python-2.7/builds/2013-12-15_15-29-59/archive/CHANGES.log
**WS = kgs-plone.app.discussion-plone-5.0-python-2

Deleting project workspace... 
done

Finished: FAILURE
```

**Comment by gforcada** [comment]
We no longer have KGS jobs AFAICS.

Closing, feel free to reopen.
